"""Note Generator — produces structured markdown notes from lecture events."""
from __future__ import annotations
import os, re
from models.schemas import (
    KeyConcept, TranscriptionEvent, SlideEvent, ImportanceLevel, LectureSession
)
from datetime import datetime


def importance_stars(score: float) -> str:
    if score > 0.85:
        return "[***]"
    elif score > 0.7:
        return "[**]"
    elif score > 0.5:
        return "[*]"
    return ""


def generate_markdown_notes(session: LectureSession) -> str:
    """Generate structured markdown notes from a lecture session."""
    duration = session.duration_seconds
    dur_str = f"{duration // 60} minutes" if duration else "In progress"
    date_str = datetime.fromtimestamp(session.start_time).strftime("%b %d, %Y %I:%M %p")

    lines = [
        f"# Lecture: {session.title}",
        f"**Date**: {date_str} | **Duration**: {dur_str}",
        "",
    ]

    # Key concepts section
    critical = [c for c in session.key_concepts if c.importance_level == ImportanceLevel.CRITICAL]
    important = [c for c in session.key_concepts if c.importance_level == ImportanceLevel.IMPORTANT]
    supporting = [c for c in session.key_concepts if c.importance_level == ImportanceLevel.SUPPORTING]

    if critical:
        lines.append("## Critical Concepts (Must Know)")
        lines.append("")
        for c in critical:
            lines.append(f"### [{c.lecture_time}] {c.title} {importance_stars(c.importance_score)}")
            lines.append(f"- **Definition**: {c.definition}")
            if c.professor_quote:
                lines.append(f'- Professor emphasized: "{c.professor_quote}"')
            if c.gesture_note:
                lines.append(f"- Gestures: {c.gesture_note}")
            if c.related_concepts:
                lines.append(f"- Related: {', '.join(c.related_concepts)}")
            if c.sources:
                lines.append(f"- Sources: {', '.join(c.sources)}")
            lines.append("")

    if important:
        lines.append("## Important Points")
        lines.append("")
        for c in important:
            lines.append(f"### [{c.lecture_time}] {c.title} {importance_stars(c.importance_score)}")
            lines.append(f"- **Definition**: {c.definition}")
            if c.professor_quote:
                lines.append(f'- Professor emphasized: "{c.professor_quote}"')
            if c.related_concepts:
                lines.append(f"- Related: {', '.join(c.related_concepts)}")
            lines.append("")

    if supporting:
        lines.append("## Supporting Details")
        lines.append("")
        for c in supporting:
            lines.append(f"- [{c.lecture_time}] **{c.title}**: {c.definition[:150]}")
        lines.append("")

    # Slide content section (from OCR)
    if session.slides:
        lines.append("## Slide Content (OCR-detected)")
        lines.append("")
        for s in session.slides:
            lines.append(f"### Slide {s.slide_number}: {s.title}")
            if s.content_text:
                lines.append(f"```")
                lines.append(s.content_text)
                lines.append(f"```")
            flags = []
            if s.has_diagram:
                flags.append("Diagram")
            if s.has_equation:
                flags.append("Equation")
            if flags:
                lines.append(f"_{' | '.join(flags)}_")
            lines.append("")

    # Importance timeline summary
    if session.importance_events:
        lines.append("## Importance Timeline")
        lines.append("")
        lines.append("| Time | Score | Level | Trigger |")
        lines.append("|------|-------|-------|---------|")
        for ie in session.importance_events:
            level_emoji = "[!]" if ie.level == ImportanceLevel.CRITICAL else "[*]" if ie.level == ImportanceLevel.IMPORTANT else "[-]"
            lines.append(f"| {ie.lecture_time} | {ie.score:.2f} | {level_emoji} {ie.level.value} | {ie.trigger_text[:60]} |")
        lines.append("")

    # Full transcript section
    if session.transcript:
        lines.append("## Full Transcript")
        lines.append("")
        for t in session.transcript:
            speaker = "Professor" if t.speaker.value == "professor" else "Student"
            emphasis = " **(emphasis)**" if t.is_emphasis_phrase else ""
            lines.append(f"**[{t.lecture_time}]** {speaker}: {t.text}{emphasis}")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by NoteFlow AI on {datetime.now().strftime('%b %d, %Y at %I:%M %p')}*")

    return "\n".join(lines)


def save_notes_to_file(session: LectureSession, output_dir: str = "notes") -> str | None:
    """Save generated notes to a markdown file and return the file path."""
    try:
        os.makedirs(output_dir, exist_ok=True)

        markdown = generate_markdown_notes(session)

        # Build filename from title and date
        safe_title = re.sub(r'[^\w\s-]', '', session.title).strip()
        safe_title = re.sub(r'[\s]+', '-', safe_title)[:50]
        date_str = datetime.now().strftime("%Y-%m-%d")
        safe_title = "".join([c if c.isalnum() else "_" for c in session.title]).strip("_")
        filename = f"lecture-{safe_title}-{date_str}-{session.id[:8]}.txt"
        file_path = os.path.join(output_dir, filename)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(markdown)

        print(f"Notes saved to: {file_path}")
        return file_path

    except Exception as e:
        print(f"Failed to save notes: {e}")
        return None
